#ifndef LEAPFROG_CONST_H 
#define LEAPFROG_CONST_H  1


#define LEAPFROG_MAX_COUNT      10000
#define LEAPFROG_MAX_DIM        3

#define LEAPFROG_STEP           1
#define LEAPFROG_TIME_SCALE     1000

#define LEAPFROG_CADR_COUNT     1000

#endif // LEAPFROG_CONST_H
